@clioAgent_HostAddress = http://localhost:6000


###

POST {{clioAgent_HostAddress}}/executeAsync/restoredb
Accept: application/json
Content-Type: application/json

{
  "Name": "studio802_net472",
  "CreatioBuildZipPath" : "C:\\CreatioProductBuild\\8.2.0.3888_SalesEnterprise_Marketing_ServiceEnterprise_Softkey_PostgreSQL_ENU.zip"
}


###
GET {{clioAgent_HostAddress}}/getBag
Accept: application/json



